config/routes.rb
Rails.application.routes.draw do 
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'foods#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  
  resources :foods
  resources :general_shopping_list, only: [:index, :update]
  put 'ingredients/:id', as: 'recipe_food_update', action: :update_two, controller: 'foods'
  resources :recipes do
    resources :recipe_foods do
    end
  end
  get 'public_recipes', action: :show_public, controller: :recipes

  get 'recipes/:id/ingredient/new', as: 'recipes_new_ingredient', action: :edit_two, controller: :recipes
  post 'recipes/:recipe_id/ingredients', as: 'recipes_create_ingredient', action: :update_two, controller: :recipes

  root "foods#index"
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods

  validates :name, presence: true
  validates :preparation_time, numericality: { only_decimal: true, greater_than_or_equal_to: 0 }
  validates :cooking_time, numericality: { only_decimal: true, greater_than_or_equal_to: 0 }
  validates :description, presence: true, length: { maximum: 1000 }

  def reduced_description
    return description if description.length < 100

    "#{description[0, 100]}..."
  end

  def steps
    description.split("\n")
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  include RecipesHelper
  load_and_authorize_resource
  before_action :set_recipe, only: %i[show edit update destroy]
  before_action :set_recipe_two, only: %i[edit_two]
  before_action :set_other_recipe, only: :update_two

  def index
    @page_title = 'Recipes Index'
    @recipes = my_recipes
  end

  def show; end

  def show_public
    @page_title = 'Public Recipes Index'
    @recipes = Recipe.includes(:user).all.where(public: true).order('created_at DESC')
  end

  def new
    @recipe = Recipe.new
  end

  def edit_two
    @food = Food.new
    @recipe_food = RecipeFood.new
  end

  def update_two
    @food = Food.new(food_params)
    @recipe_food = RecipeFood.new(ingredient_params)
    @food.user = current_user
    respond_to do |format|
      if @food.save
        @recipe_food.recipe = @recipe
        @recipe_food.food = @food
        @recipe_food.save
        flash[:success] = 'Food was successfully added to recipe.'
        format.html { redirect_to recipe_url(@recipe) }
        format.json { render :show, status: :created, location: @food }
      else
        flash[:error] = 'Error: Food could not be added to recipe.'
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user

    respond_to do |format|
      if @recipe.save
        flash[:success] = 'Recipe saved succesfully'
        format.html { redirect_to recipe_url(@recipe) }
        format.json { render :show, status: :created, location: @recipe }
      else
        flash[:error] = 'Error: Recipe could not be saved'
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        flash[:success] = 'Recipe has been updated successfully'
        format.html { redirect_to recipe_url(@recipe) }
        format.json { render :show, status: :ok, location: @recipe }
      else
        flash[:error] = 'Error: Recipe could not be updated'
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recipe.destroy

    flash[:success] = 'Recipe has been deleted successfully'
    redirect_to recipes_url
  end

  private

  def set_recipe
    @recipe = Recipe.includes(:recipe_foods, recipe_foods: :food).find(params[:id])
  end

  def set_recipe_two
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price)
  end

  def ingredient_params
    params.require(:recipe_food).permit(:quantity)
  end

  def set_other_recipe
    @recipe = Recipe.find(params[:recipe_id])
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
  def my_recipes
    current_user.recipes
  end
end

app/views/recipes/_food_row.html.erb
<tr id="<%= dom_id recipe_food%>">
    <th scope="row" class='align-middle'><%= food.name%></th>
    <td class='align-middle'><%= recipe_food.quantity%></td>
    <td class='align-middle'>$<%= food.price%></td>
    <td class='d-flex align-middle'>
      <% if can? :manage, @recipe %>
        <%= link_to 'Edit ingredient', edit_recipe_recipe_food_path(recipe_food.recipe_id, food.id),
        class:"btn btn-warning me-2" %>
        <%= button_to "Remove food", recipe_recipe_food_path(recipe_food.recipe_id, recipe_food.id),
          class:"btn btn-danger", method: :delete %>
        <% else%>
        <button class="btn disabled">No action</button>
      <% end %>
    </td>    
</tr>

app/views/recipes/_ingredient_form.html.erb
<%= form_with(model: [@food, @recipe_food], url: recipes_create_ingredient_path(@recipe), method: :post, scope: @food, 
  html: { class: 'ingredient-form-create' }, data: { turbo: false }) do |form| %>
  <% if @food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% @food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %> 
  <% if @recipe_food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@recipe_food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% @recipe_food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %> 
  
  <div class="field mb-3">
    <%= form.label :name %>
    <%= form.text_field :name, placeholder: "Enter the food", class: 'form-control' %>
  </div>
   <div class="field mb-3">
    <%= form.label :measurement_unit %>
    <%= form.text_field :measurement_unit, placeholder: "Enter the measurement unit", class: 'form-control' %>
  </div>
  <div class="field mb-3">
    <%= form.label :price %>
    <%= form.text_field :price, placeholder: "Enter the price", class: 'form-control' %>
  </div>    
  <div class="field mb-3">
    <%= form.label :quantity %>
    <%= form.text_field :quantity, name: 'recipe_food[quantity]', placeholder: "Enter a quantity", class: 'form-control' %>
  </div>    
    
    <%= form.submit 'Submit', class:"btn btn-primary"%>

<% end %>

app/views/recipes/_public_recipe.html.erb
<%= link_to recipe, {:style => 'text-decoration: none; color: black'} do%>
  <div class="card flex-row mb-2" style='height: 120px' id="<%= dom_id recipe %>">
    <div class="card-body w-50 d-flex flex-column justify-content-center">
      <h3 class="card-title m-2"><%= recipe.name %></h3>
      <h4 class="m-2">By: <%= recipe.user.name %></h4>
    </div>
    <div class="card-body w-50 d-flex flex-column">
      <h5>Total food items: <%= recipe.foods.count %></h5>
      <h5>Total price: $<%= recipe.foods.sum(:price) %></h5>
    </div>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<%= link_to recipe, {:style => 'text-decoration: none; color: black'} do%>
  <div class="card flex-row mb-2" style='height: 120px' id="<%= dom_id recipe %>">
    <div class="card-body w-50 d-flex flex-column justify-content-center">
      <h3 class="card-title m-2"><%= recipe.name %></h3>
      <% if can? :destroy, recipe %> 
        <%= button_to "Delete recipe", recipe_path(recipe.id), 
          class:"btn btn-outline-danger float-right m-2 mr-5", method: :delete %> 
      <% end %> 
    </div>
    <div class="card-body w-50 d-flex flex-column">
      <h4>Description:</h4>
      <%= recipe.reduced_description %>
    </div>
  </div>
<% end %>

   

app/views/recipes/_recipe_foods.html.erb
<div id="<%= dom_id recipe%>" >
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">Food</th>
          <th scope="col">Quantity</th>
          <th scope="col">Value</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
      <% if recipe.recipe_foods.any? %>
        <% recipe.recipe_foods.each do |recipe_food| %>
          <%= render partial: "food_row", locals: {:food => recipe_food.food, :recipe_food => recipe_food} %> 
        <% end %>
      <% else %>
        <h4>No foods have been added yet to this recipe.</h4>
      <% end %>
      </tbody>             
    </table>
  </div>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= form_with model: @recipe, url: recipe_path, method: :put, scope: @recipe, html: { class: 'recipe-form-new' } do |f| %>
  <% if @recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being updated:</h2>

      <ul>
        <% @recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %> 
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, placeholder: 'Enter name...' %>
  </div>
  
  <div class="field">
    <%= f.label :preparation_time %> <em>(in minutes)</em><br />
    <%= f.number_field :preparation_time, step: '0.1' %>
  </div>

  <div class="field">
    <%= f.label :cooking_time %> <em>(in minutes)</em><br />
    <%= f.number_field :cooking_time, step: '0.1' %>
  </div>
  
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, placeholder: 'Enter a description...', class: 'w-75 min-vw-50', style: 'height: 80px' %>
  </div>
  <br>
  
  <div class="field form-switch ps-0">
    <%= f.label :public, for: 'publicSwitchCheck' %>:
    <%= f.check_box :public, class: 'form-check-input ms-0', id: 'publicSwitchCheck' %>
  </div>
  
</label>

  <br>
  <div class="actions">
    <%= f.submit "Update Recipe" %>
  </div>
<% end %>
<br>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/edit_two.html.erb
<h1>Create new ingredient</h1>
<h4>Will be added to recipe: <%= @recipe.name %></h4>

<%= render "ingredient_form" %>

<br>
<div>
  <%= link_to "Go back", :back %>
</div>

app/views/recipes/index.html.erb
<div class="page-title d-flex align-items-center">
  <h1><%= @page_title %></h1>
  <%= link_to "Create Recipe", new_recipe_path, class: 'btn btn-outline-primary ms-4' %>
</div>
<hr>

<div id="recipes-list d-flex flex-column">
  <% @recipes.each do |recipe| %>
    <%= render recipe %>
  <% end %>
</div>

app/views/recipes/new.html.erb
<h1>New food</h1>

<%= form_with model: @recipe, url: recipes_path, method: :post, scope: @recipe, html: { class: 'recipe-form-new' } do |f| %>
  <% if @recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% @recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %> 
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, placeholder: 'Enter name...' %>
  </div>
  
  <div class="field">
    <%= f.label :preparation_time %> <em>(in minutes)</em><br />
    <%= f.number_field :preparation_time, step: '0.1', value: 0.0 %>
  </div>

  <div class="field">
    <%= f.label :cooking_time %> <em>(in minutes)</em><br />
    <%= f.number_field :cooking_time, step: '0.1', value: 0.0 %>
  </div>
  
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, placeholder: 'Enter a description...', class: 'w-75 min-vw-50', style: 'height: 80px' %>
  </div>
  <br>
  
  <div class="field form-switch ps-0">
    <%= f.label :public, for: 'publicSwitchCheck' %>:
    <%= f.check_box :public, class: 'form-check-input ms-0', id: 'publicSwitchCheck' %>
  </div>
  
</label>

  <br>
  <div class="actions">
    <%= f.submit "Add Recipe" %>
  </div>
<% end %>
<br>

<div>
  <%= link_to "Go back", :back %>
</div>

app/views/recipes/show.html.erb
<div class="page-title d-flex align-items-center">
  <h1>Recipes Show</h1>
</div>
<hr>

<div class="recipe-details position-relative">
  <h2><%= @recipe.name %></h2>
  <h4>Preparation Time: <%= @recipe.preparation_time %> minutes</h4>
  <h4>Cooking Time: <%= @recipe.cooking_time %> minutes</h4>
  <h4>Steps: </h4>
  <% @recipe.steps.each do |step| %>
    <p><%= step %></p>
  <% end %>
  <%= form_with model: @recipe, url: recipe_path, method: :put, scope: @recipe, 
  html: { class: 'recipe-form-details position-absolute top-0 end-0' } do |f| %>
    <div class="field form-switch ps-0">
      <%= f.label "Public:", for: 'public-switch-check' %>
      <%= f.check_box :public, class: 'form-check-input ms-2', id: 'public-switch-check' %>
    </div>
    <% if can? :manage, @recipe %>
      <%= f.submit "Set this public state" %>
      <% end %>
  <% end %>
</div>

<div class="action-buttons w-100 d-flex justify-content-between">
  
  <%= form_with url: general_shopping_list_path(current_user.id, :recipe => @recipe.id), method: :put do |f| %>
    <%= f.submit "Generate Shopping List", class: 'btn btn-primary' %>
  <% end %>
  <% if can? :manage, @recipe %>
    <%= link_to "Add ingredient",  new_recipe_recipe_food_path(@recipe), 
      class: 'btn btn-secondary' %>
  <% end %>

</div>
<hr>

<%= render "recipe_foods", recipe: @recipe %>

<div>
  <%= link_to "Edit this recipe", edit_recipe_path(@recipe) %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/show_public.html.erb
<div class="page-title d-flex align-items-center">
  <h1><%= @page_title %></h1>
  <%= link_to "Create Recipe", new_recipe_path, class: 'btn btn-outline-primary ms-4' %>
</div>
<hr>

<div id="recipes-list d-flex flex-column">
  <% @recipes.each do |recipe| %>
    <%= render 'public_recipe', recipe: recipe %>
  <% end %>
</div>