config/routes.rb
Rails.application.routes.draw do 
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'foods#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  
  resources :foods
  resources :general_shopping_list, only: [:index, :update]
  put 'ingredients/:id', as: 'recipe_food_update', action: :update_two, controller: 'foods'
  resources :recipes do
    resources :recipe_foods do
    end
  end
  get 'public_recipes', action: :show_public, controller: :recipes

  get 'recipes/:id/ingredient/new', as: 'recipes_new_ingredient', action: :edit_two, controller: :recipes
  post 'recipes/:recipe_id/ingredients', as: 'recipes_create_ingredient', action: :update_two, controller: :recipes

  root "foods#index"
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :recipes, through: :recipe_foods

  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :price, presence: true, numericality: { only_decimal: true, greater_than: 0 }
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[show edit update update_two destroy]
  load_and_authorize_resource

  # GET /foods or /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1 or /foods/1.json
  def show; end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit; end

  # POST /foods or /foods.json
  def create
    @food = Food.new(food_params)
    @food.user = current_user
    respond_to do |format|
      if @food.save
        flash[:success] = 'Food has been created successfully'
        format.html { redirect_to food_url(@food) }
        format.json { render :show, status: :created, location: @food }
      else
        flash[:error] = 'Error: Food could not be created'
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1 or /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        flash[:success] = 'Food has been updated successfully'
        format.html { redirect_to food_url(@food) }
        format.json { render :show, status: :ok, location: @food }
      else
        flash[:error] = 'Error: Food could not be updated'
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_two
    respond_to do |format|
      if @food.update(recipe_food_params)
        flash[:success] = 'Recipe food has been updated successfully'
        format.html { redirect_to recipe_url(params[:recipe]) }
      else
        flash[:error] = 'Error: Recipe food could not be updated'
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @food.destroy

    respond_to do |format|
      flash[:success] = 'Food has been destroyed successfully'
      format.html { redirect_to foods_url }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.fetch(:food, {}).permit(:name, :measurement_unit, :price)
  end

  def recipe_food_params
    params.require(:food).permit(:quantity, :price)
  end
end

app/views/foods/_food.html.erb
<tbody>
  <tr id="<%= dom_id food%>">
      <th scope="row"><%= food.name%></th>
      <td><%= food.measurement_unit%></td>
      <td>$<%= food.price%></td>
      <td>
        <% if can? :destroy, food %>
        <%= button_to "Delete food", food_path(food.id),
          class:"btn btn-outline-danger float-right", method: :delete %>
          <% else%>
          <button class="btn disabled">No action</button>
        <% end %>
      </td>    
  </tr>
</tbody>

app/views/foods/_form.html.erb
<%= form_with(model: food, url: foods_path, data: { turbo: false }) do |form| %>
  <% if food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %> 
  
  <div class="mb-3">
    <%= form.label :name %>
    <%= form.text_field :name, placeholder: "Enter the food", class: 'form-control' %>
  </div>
   <div class="mb-3">
    <%= form.label :measurement_unit %>
    <%= form.text_field :measurement_unit, placeholder: "Enter the measurement unit", class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= form.label :price %>
    <%= form.text_field :price, placeholder: "Enter the price", class: 'form-control' %>
  </div>    
    
    <%= form.submit 'Submit', class:"btn btn-primary"%>

<% end %>

app/views/foods/edit.html.erb
<h1>Editing food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Show this food", @food %> |
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/index.html.erb
<div>
  <h1 class="text-center">Foods</h1>
  <hr>
  <div class="d-flex justify-content-end">
    <%= link_to "New food", new_food_path, class: 'btn btn-outline-primary'%>
  </div>
  <div id="foods">
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">Food</th>
          <th scope="col">Measurement unit</th>
          <th scope="col">Unit price</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>      
        <% @foods.each do |food| %>
          <%= render food %>  
        <% end %>      
    </table>
  </div>
</div>

app/views/foods/new.html.erb
<h1>New food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/show.html.erb
<h2>Food Details</h2>
<div>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Food</th>
        <th scope="col">Measurement unit</th>
        <th scope="col">Unit price</th>
        <th scope="col">Actions</th>
      <tr>
    </thead>   
    <%= render "food", food: @food %>
  </table>
</div>

<div>  
  <%= link_to "Back to foods", foods_path %>  
</div>