config/routes.rb
Rails.application.routes.draw do 
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'foods#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  
  resources :foods
  resources :general_shopping_list, only: [:index, :update]
  put 'ingredients/:id', as: 'recipe_food_update', action: :update_two, controller: 'foods'
  resources :recipes do
    resources :recipe_foods do
    end
  end
  get 'public_recipes', action: :show_public, controller: :recipes

  get 'recipes/:id/ingredient/new', as: 'recipes_new_ingredient', action: :edit_two, controller: :recipes
  post 'recipes/:recipe_id/ingredients', as: 'recipes_create_ingredient', action: :update_two, controller: :recipes

  root "foods#index"
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food
  belongs_to :recipe
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :set_recipe, only: %i[new create show edit update destroy]
  before_action :set_recipe_food, only: %i[show edit update destroy]
  load_and_authorize_resource

  def edit
    @food = Food.find(@recipe_food.food_id)
  end

  def update
    respond_to do |format|
      if @recipe_food.update(recipe_food_params)
        flash[:success] = 'Recipe food has been updated successfully'
        format.html { redirect_to recipe_url(@recipe) }
      else
        flash[:error] = 'Error: Recipe food could not be updated'
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def create
    @recipe_food = RecipeFood.new(ingredient_params)
    @recipe_food.recipe = @recipe
    @recipe_food.food = Food.find(params[:food_id])
    respond_to do |format|
      if @recipe_food.save
        flash[:success] = 'Ingredient saved succesfully'
        format.html { redirect_to recipe_url(@recipe) }
        format.json { render :show, status: :created, location: @recipe }
      else
        flash[:error] = 'Error: Ingredient could not be saved'
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recipe_food.destroy

    flash[:success] = 'Recipe food has been deleted successfully'
    redirect_to recipe_url(@recipe.id)
  end

  private

  def recipe_food_params
    params.require(:recipe_food).permit(:quantity, :value)
  end

  def set_recipe
    @recipe = Recipe.find(params[:recipe_id])
    @foods = current_user.foods
  end

  def set_recipe_food
    @recipe_food = RecipeFood.find_by(food_id: params[:id])
  end

  def ingredient_params
    params.require(:recipe_food).permit(:quantity)
  end
end

app/views/recipe_foods/_food_row.html.erb
<%= form_with model: @recipe_food, url: recipe_recipe_foods_path(@recipe, :food_id => food.id), method: :post, 
  scope: @recipe_food, html: { class: 'recipe-food-form-edit' } do |f| %>
  <% if @recipe_food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@recipe_food.errors.count, "error") %> prohibited this recipe food from being saved:</h2>

      <ul>
        <% @recipe_food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %> 
  <tr class="row px-3 mx-0">
    <td class="col-4 mb-1"><%= food.name %></td>
    <td class="col-2 mb-1"><%= food.measurement_unit %></td>
    <td class="col-2 mb-1 me-3"><%= f.number_field :quantity, step: '0.1', class: 'w-100' %></td>
    <td class="col-3 mb-1 p-0"><%= f.submit 'Add ingredient', class: 'p-1 btn btn-success text-white' %></td>
  </tr>
<% end %>

app/views/recipe_foods/_form_food_table.html.erb
<table class="foods-table container border border-dark border-2">
  <tr class="row px-3 label-row mx-0">
    <th class="col-4">Food</th>
    <th class="col-2">Measurement Unit</th>
    <th class="col-2">Quantity</th>
    <th class="col-4">Action</th>
  </tr>
  <% foods.each do |food| %>
    <%= render 'food_row', food: food, recipe_food: recipe_food %>
  <% end %>
</table>

app/views/recipe_foods/edit.html.erb
<h1>Edit Recipe Food</h1>

<h2>You are editing <%= @recipe.name %></h2>

<div class="recipe-food-update-forms container-fluid d-flex">
  <%= form_with model: @recipe_food, url: recipe_recipe_food_path(@recipe, @recipe_food), method: :put, scope: @recipe_food, html: { class: 'recipe-food-form-edit' } do |form| %>
    <% if @recipe_food.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(@recipe_food.errors.count, "error") %> prohibited this recipe food from being saved:</h2>

        <ul>
          <% @recipe_food.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %> 
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">Food</th> <th scope="col">Quantity <em>(<%= @food.measurement_unit %>)</em></th>
        </tr>
      </thead>
      <tbody>
        <tr id="<%= dom_id @recipe_food%>">
          <th scope="row"><%= @food.name%></th>
          <td>
            <div class="field">
              <%= form.text_field :quantity, placeholder: "Enter a quantity", class: 'form-control' %>
            </div>
          </td>
        </tr>
      </tbody>             
    </table>
    <br>
    <div class="actions">
      <%= form.submit "Update Quantity" %>
    </div>
  <% end %>
  <%= form_with model: @food, url: recipe_food_update_path(@food, :recipe => @recipe), method: :put, scope: @food, html: { class: 'food-form-edit' } do |form| %>
    <% if @food.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(@food.errors.count, "error") %> prohibited this recipe food from being updated:</h2>

        <ul>
          <% @food.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">Value <em>(USD $)</em></th>
        </tr>
      </thead>
      <tbody>
        <tr id="<%= dom_id @food%>">
          <td>
            <div class="field">
              <%= form.text_field :price, placeholder: "Enter a price", class: 'form-control' %>
            </div>
          </td>
        </tr>
      </tbody>             
    </table>
    <br>
    <div class="actions">
      <%= form.submit "Update Value" %>
    </div>
  <% end %>
</div>
<br>

<div>
  <%= link_to "Go back", :back %>
</div>

app/views/recipe_foods/new.html.erb
<h2>Add Ingredient!</h2>
<div>
  <%= render 'form_food_table', recipe_food: @recipe_food, foods: @foods %>

  <%= link_to "Create new ingredient",  recipes_new_ingredient_path(@recipe), class: 'btn btn-secondary' %>
  
</div>
<div class="d-flex my-3">
  <%= link_to 'Go back' , recipe_path(@recipe),
    class: "btn btn-secondary" %>
</div>