config/routes.rb
Rails.application.routes.draw do 
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'foods#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  
  resources :foods
  resources :general_shopping_list, only: [:index, :update]
  put 'ingredients/:id', as: 'recipe_food_update', action: :update_two, controller: 'foods'
  resources :recipes do
    resources :recipe_foods do
    end
  end
  get 'public_recipes', action: :show_public, controller: :recipes

  get 'recipes/:id/ingredient/new', as: 'recipes_new_ingredient', action: :edit_two, controller: :recipes
  post 'recipes/:recipe_id/ingredients', as: 'recipes_create_ingredient', action: :update_two, controller: :recipes

  root "foods#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    
  </head>

  <body class="container position-relative">
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand">RecipeApp</a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav container-fluid">
          <li class="nav-item">
            <%= link_to "Foods", foods_path, :class => current_class?(foods_path) %>
          </li>
          <li class="nav-item">
            <%= link_to "My Recipes", recipes_path, :class => current_class?(recipes_path) %>
          </li>
          <li class="nav-item">
            <%= link_to "Public Recipes", public_recipes_path, :class => current_class?(public_recipes_path) %>
          </li>
          <li class="nav-item">
            <%= link_to "Shopping List", general_shopping_list_index_path, :class => current_class?(general_shopping_list_index_path) %>
          </li>
          <% if signed_in? %>
            <li class="nav-item ms-lg-auto">
              <%= link_to "Edit User", edit_user_registration_path, class: 'nav-link' %>              
            </li>
            <li class="nav-item d-flex align-items-center">
              <%= button_to "Log Out", destroy_user_session_path, class: 'bg-transparent nav-link px-1 py-0 ', method: :delete  %>              
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <br>
  <br>
  <br>
  <% flash.each do |name, msg| -%>
    <%= content_tag :div, msg, class: "alert alert-#{name}" %>
  <% end -%>
  <% if user_signed_in? %>
    <div class="position-absolute top-10 end-0">
      Logged in as <strong><%= current_user.email %></strong>
    </div>
  <% end %>
  <%= yield %>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    
  </head>

  <body class="container">    
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>